apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gitautomation.fullname" . }}
  labels:
    app: {{ template "gitautomation.name" . }}
    chart: {{ template "gitautomation.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gitautomation.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gitautomation.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: gitcredentials
            mountPath: "/run/secrets/gitcredentials"
            readOnly: true
          - name: configuration.json
            mountPath: "/run/secrets/configuration.json"
            readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: gitcredentials
        secret:
          secretName: {{ required ".Values.gitCredentials.secretName must be supplied" .Values.gitCredentials.secretName }}
          items:
          - key: {{ required ".Values.gitCredentials.key must be supplied" .Values.gitCredentials.key }}
            defaultMode: 0400
      - name: configuration.json
        secret:
          secretName: {{ required ".Values.config.secretName must be supplied" .Values.config.secretName }}
          items:
          - key: {{ required ".Values.config.key must be supplied" .Values.config.key }}
            defaultMode: 0400