language: c
sudo: required

install:
- docker pull microsoft/aspnetcore-build:2.0
- docker build -t travis-docker -f Dockerfile-ci .
- docker build -t travis-docker-psql -f ./GitAutomation.Postgres/Dockerfile-ci ./GitAutomation.Postgres

script:
#only build if tests succeed
#(NB: the script/build is run *outside* a container in the following command)
- docker run -v "$(pwd):/src" -w="/src" --rm travis-docker
- docker run -v "$(pwd)/GitAutomation.Postgres:/src" -w="/src" --rm travis-docker-psql

# TODO - v1.0.0
#after_success:
#- docker build -t travis-docker-prod -f Dockerfile.prod .
#- TODO - upload to docker hub
