language: c
sudo: required

install:
- echo "branch ${TRAVIS_BRANCH} tag ${TRAVIS_TAG}"
- TAG=$(./ci/branch-to-tag.sh)
- echo "installing tag ${TAG}"
- docker-compose -f docker-compose.ci.build.yml up --build

script:
- echo "building tag ${TAG}"
- docker-compose -f docker-compose.yml -f docker-compose.build.yml build
# TODO - re-tag images

# after_success:
# - echo "publishing tag ${TAG}"
# - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
# - docker push ${DOCKER_USERNAME}/gitautomation${TAG}
# - docker push ${DOCKER_USERNAME}/gitautomation-psql${TAG}
