language: c
sudo: required

install:
- docker pull microsoft/aspnetcore-build:2.0
- docker build -t travis-docker -f Dockerfile-ci .
- docker build -t travis-docker-psql -f ./GitAutomation.Postgres/Dockerfile-ci ./GitAutomation.Postgres

script:
- docker run -v "$(pwd):/src" -w="/src" --rm travis-docker
- docker run -v "$(pwd)/GitAutomation.Postgres:/src" -w="/src" --rm travis-docker-psql
# Splits the branch by `/`
- PARTS=(${TRAVIS_BRANCH//\// });
  TAG=dev
  if [ "${PARTS[0]}" == "rel" ]; then
    TAG=:${PARTS[1]};
  fi;
  if [ "${PARTS[0]}" == "line" ]; then
    TAG=:${PARTS[1]};
  fi
- docker build -t gitautomation${TAG} -f ./GitAutomation/Dockerfile ./GitAutomation
- docker build -t gitautomation-psql${TAG} -f ./GitAutomation.Postgres/Dockerfile ./GitAutomation.Postgres

after_success:
- echo "publishing tag ${TAG}"
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push ${DOCKER_USERNAME}/gitautomation${TAG}
- docker push ${DOCKER_USERNAME}/gitautomation-psql${TAG}
