language: c
sudo: required
services: docker

install:
- echo "branch ${TRAVIS_BRANCH} tag ${TRAVIS_TAG}"
- TAG=$(./ci/branch-to-tag.sh)
- echo "installing tag ${TAG}"
- sudo docker-compose -f docker-compose.ci.build.yml up --build

script:
- echo "building tag ${TAG}"
- sudo docker-compose -f docker-compose.yml -f docker-compose.build.yml -f docker-compose.sqlserver.yml build

after_success:
 - echo "publishing tag ${TAG} for images:"
 - docker images | grep gitautomation/ | grep latest | awk '{print $1}'
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - for image in $(docker images | grep gitautomation/ | grep latest | awk '{print $1}'); do
     docker tag $image:latest $image$TAG;
     docker push $image$TAG;
   done
