version: '3.1'

services:
  gitautomation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - "./GitAutomation.AllAddons/bin/Debug/netcoreapp2.0:/extra-bins/all-addons"
      
  gitautomation-sql:
    ports:
      - "21433:1433"
      
  gitautomation-psql:
    ports:
      - "5432:5432"

  git-server:
    image: testing-git-server
    ports:
      - "8082:80"

# TODO - define networks to prevent git-server from accessing gitautomation-sql
