FROM microsoft/aspnetcore-build:2.0

RUN apt-get update && apt-get install -y \
  nodejs

RUN apt-get update && apt-get install -y curl apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn


CMD /bin/bash -c "cd GitAutomation\
  && yarn && yarn build --env.NODE_ENV=production\
  && cd ..\
  && dotnet restore ./GitAutomation.sln && dotnet publish ./GitAutomation.sln -c ci-docker -o ./obj/Docker/publish\
  && cd GitAutomation.Postgres\
  && dotnet ef migrations script --context GitAutomation.EFCore.SecurityModel.SecurityContext -o obj/Docker/publish/init-security.sql\
  && dotnet ef migrations script --context GitAutomation.EFCore.BranchingModel.BranchingContext -o obj/Docker/publish/init-branching.sql"
