version: '3.1'

services:
  ci-build:
    image: gitautomation:build
    build:
      context: .
      dockerfile: Dockerfile-ci
    volumes:
      - .:/src
    working_dir: /src
  
  gitautomationsql-ci:
    image: gitautomation-sql:build
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile-ci
    volumes:
      - ./GitAutomation.Sql:/src
    working_dir: /src
    
  gitautomationpsql-ci:
    image: gitautomation-psql:build
    build:
      context: ./GitAutomation.Postgres
      dockerfile: Dockerfile-ci
    volumes:
      - ./GitAutomation.Postgres:/src
    working_dir: /src
