version: '3.1'

services:
  web:
    depends_on:
      - sql-addon

  sql:
    image: gitautomation/sql-host
    build:
      context: ./GitAutomation.SqlServer
      dockerfile: Dockerfile
    ports:
      - "21433:1433"
    secrets:
      - sqlcredentials
      - sqleula

  sql-addon:
    image: gitautomation/sql-addon
    volumes:
      - "addons:/export"

secrets:
  sqlcredentials:
    file: ./sql-credentials.txt
  sqleula:
    file: ./sql-eula.txt