version: '3.1'

# VS2017 update 3 chokes if the context of non-.Net containers is present. Use this file to build them.
# https://developercommunity.visualstudio.com/content/problem/96130/solution-build-fails-with-docker-compose-error-in.html
services:
  gitautomation-sql:
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile

  gitautomation-psql:
    build:
      context: ./GitAutomation.Postgres
      dockerfile: Dockerfile

# TODO - define networks to prevent git-server from accessing gitautomation-sql
