version: '3.1'

services:
  ci-build:
    image: gitautomation/web:build
    build:
      context: .
      dockerfile: Dockerfile-ci
    volumes:
      - .:/src
    working_dir: /src

  sql-ci:
    image: gitautomation/sql-host:build
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile-ci
    volumes:
      - ./GitAutomation.Sql:/src

  psql-ci:
    image: gitautomation/psql-host:build
    build:
      context: ./GitAutomation.Postgres
      dockerfile: Dockerfile-ci
    volumes:
      - ./GitAutomation.Postgres:/src
