version: '3.1'

services:
  gitautomation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  gitautomation-sql:
    ports:
      - "21433:1433"

  git-server:
    image: testing-git-server
    ports:
      - "8082:80"

# TODO - define networks to prevent git-server from accessing gitautomation-sql
