version: '3.1'

services:
  gitautomation-sql:
    image: gitautomation-sql
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile
    ports:
      - "21433:1433"
    secrets:
      - sqlcredentials
      - sqleula

secrets:
  sqlcredentials:
    file: ./sql-credentials.txt
  sqleula:
    file: ./sql-eula.txt