version: '3.1'

services:
  gitautomation-sql:
    build:
      context: ./GitAutomation.Sql
      dockerfile: Dockerfile
  git-server:
    image: testing-git-server
    build:
      context: ./git-server
      dockerfile: dockerfile

secrets:
  gitcredentials:
    file: ./git-credentials.txt
  sqlcredentials:
    file: ./sql-credentials.txt
  sqleula:
    file: ./sql-eula.txt
  configuration.json:
    file: ./configuration.json

#networks:
#  backend:
