version: '3.1'

# VS2017 update 3 chokes if the context of non-.Net containers is present. Use this file to build them.
# https://developercommunity.visualstudio.com/content/problem/96130/solution-build-fails-with-docker-compose-error-in.html
services:
  git-server:
    image: testing-git-server
    build:
      context: ./git-server
      dockerfile: Dockerfile

  psql:
    image: gitautomation/psql-host
    build:
      context: ./GitAutomation.Postgres
      dockerfile: Dockerfile

  psql-addon:
    image: gitautomation/psql-addon
    build:
      context: ./
      dockerfile: Dockerfile-addon
      args:
        subfolder: GitAutomation.Postgres

  sql-addon:
    image: gitautomation/sql-addon
    build:
      context: ./
      dockerfile: Dockerfile-addon
      args:
        subfolder: GitAutomation.SqlServer

  github-addon:
    image: gitautomation/github-addon
    build:
      context: ./
      dockerfile: Dockerfile-addon
      args:
        subfolder: GitAutomation.GitHub

secrets:
  gitcredentials:
    file: ./git-credentials.txt
  configuration.json:
    file: ./configuration.json

#networks:
#  backend:
