version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

#  sql:
#    ports:
#      - "21433:1433"

  psql:
    ports:
      - "5432:5432"

  git-server:
    image: testing-git-server
    ports:
      - "8082:80"

# TODO - define networks to prevent git-server from accessing sql
