FROM microsoft/aspnetcore-build:2.0

RUN apt-get update && apt-get install -y \
  nodejs

RUN apt-get update && apt-get install -y curl apt-transport-https && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn

WORKDIR /var/build

COPY GitAutomation/package.json GitAutomation/yarn.lock ./GitAutomation/
RUN cd GitAutomation && yarn && cd ..

COPY **/*.csproj *.sln ./
RUN dotnet restore ./GitAutomation.sln

CMD ./ci/build-and-test.sh
