version: '3.1'

services:
  ci-build:
    image: gitautomation/web:build
    build:
      context: .
      dockerfile: Dockerfile-ci
    volumes:
      - .:/src
      - ./.docker-yarn-cache:/root/yarn-cache
      - ./linux-node-modules:/src/GitAutomation/node_modules
    working_dir: /src
