FROM microsoft/mssql-server-linux:latest

WORKDIR /src

# Needs environment variables set up;
# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
CMD /bin/bash -c "./ci-entry.sh"
