FROM microsoft/mssql-server-linux:rc2

WORKDIR /working
COPY shared-scripts/*.sh ./
COPY build-scripts/*.sh ./
COPY *.sql ./

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=weakPASSw0rd

# Needs environment variables set up;
# https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
RUN /bin/bash -c "./ci-entry.sh"

CMD /bin/bash -c "cp -R /out/* /src"
