version: '3.1'

services:
  web:
    image: gitautomation/web
    secrets:
      - gitcredentials
      - configuration.json
    ports:
      - "8080:80"
    volumes:
      - "addons:/extra-bins"
    depends_on:
      - psql-addon
      - github-addon

  psql:
    image: gitautomation/psql-host
    volumes:
      - ./postgres-data:/var/lib/postgresql

  psql-addon:
    image: gitautomation/psql-addon
    volumes:
      - "addons:/export"

  github-addon:
    image: gitautomation/github-addon
    volumes:
      - "addons:/export"

secrets:
  gitcredentials:
    file: ./git-credentials.txt
  configuration.json:
    file: ./configuration.json

# docker volume create --name gitautomation-postgresql-volume -d local
volumes:
  gitautomation-postgresql-volume:
    external: true
  addons: {}