version: '3.1'

services:
  gitautomation:
    image: gitautomation
    secrets:
      - gitcredentials
      - configuration.json
    ports:
      - "8080:80"

  gitautomation-psql:
    image: gitautomation-psql
    volumes:
      - gitautomation-postgresql-volume:/var/lib/postgresql/data

secrets:
  gitcredentials:
    file: ./git-credentials.txt
  configuration.json:
    file: ./configuration.json

# docker volume create --name gitautomation-postgresql-volume -d local
volumes:
  gitautomation-postgresql-volume:
    external: true
