FROM postgres:9.6


WORKDIR /working
COPY scripts/shared/*.sh ./
COPY scripts/build/*.sh ./
COPY *.sql /docker-entrypoint-initdb.d/

ENV POSTGRES_PASSWORD=weakPASSw0rd

RUN /bin/bash -c "./ci-entry.sh"

CMD /bin/bash -c "cp -R /out/* /src"
