version: '3.1'

services:
  gitautomation-sql:
    image: gitautomation-sql
    build:
      context: ../GitAutomation.Sql
      dockerfile: Dockerfile
    secrets:
      - sqlcredentials
      - sqleula
    ports: 
      - "31433:1433"
  testing-git-server:
    image: testing-git-server
    build:
      context: ../git-server
      dockerfile: dockerfile
    ports:
      - "8081:80"

secrets:
  sqlcredentials:
    file: ./sql-credentials.txt
  sqleula:
    file: ../sql-eula.txt
