version: '3.1'

services:
  test-sql:
    image: gitautomation/sql-host
    secrets:
      - sqlcredentials
      - sqleula
    ports:
      - "31433:1433"

secrets:
  sqlcredentials:
    file: ./sql-credentials.txt
  sqleula:
    file: ../sql-eula.txt
