// <auto-generated />
using GitAutomation.EFCore.SecurityModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GitAutomation.Postgres.SecurityMigrations
{
    [DbContext(typeof(SecurityContext))]
    [Migration("20171016122131_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("GitAutomation.EFCore.SecurityModel.User", b =>
                {
                    b.Property<string>("ClaimName")
                        .HasColumnName("claimname")
                        .HasMaxLength(256);

                    b.HasKey("ClaimName");

                    b.ToTable("claimeduser");
                });

            modelBuilder.Entity("GitAutomation.EFCore.SecurityModel.UserRole", b =>
                {
                    b.Property<string>("ClaimName")
                        .HasColumnName("claimname")
                        .HasMaxLength(256);

                    b.Property<string>("Role")
                        .HasColumnName("role")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("ClaimName", "Role");

                    b.ToTable("userrole");
                });

            modelBuilder.Entity("GitAutomation.EFCore.SecurityModel.UserRole", b =>
                {
                    b.HasOne("GitAutomation.EFCore.SecurityModel.User", "ClaimNameNavigation")
                        .WithMany("UserRole")
                        .HasForeignKey("ClaimName")
                        .HasConstraintName("FK_UserRole_ToUser");
                });
#pragma warning restore 612, 618
        }
    }
}
